### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10,1)
print("Вектор-стовпець vector:")
print(vector)
print(f"\nРозмір вектора {vector.shape}")

Вектор-стовпець vector:
[[0.59265007]
 [0.47889521]
 [0.66460778]
 [0.47150122]
 [0.82614336]
 [0.30796583]
 [0.92877442]
 [0.28881642]
 [0.9561923 ]
 [0.61529256]]

Розмір вектора (10, 1)


In [3]:
matrix = np.array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]])
print("Матриця matrix:")
print(matrix)
print(f"\nРозмір матриці {matrix.shape}")

Матриця matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розмір матриці (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
# 1. Додання до вектора константи 10
vector_add_const = np.round(10 + vector,2)
print("Вектор vector після додання константи 10:")
print(vector_add_const)

Вектор vector після додання константи 10:
[[10.59]
 [10.48]
 [10.66]
 [10.47]
 [10.83]
 [10.31]
 [10.93]
 [10.29]
 [10.96]
 [10.62]]


In [5]:
# 2. Множення матриці на константу 2
matrix_mult_const = 2 * matrix
print("Матриця matrix після множення на константу 2:")
print(matrix_mult_const)

Матриця matrix після множення на константу 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [6]:
# 3. Піднесення кожного елемента вектора до квадрату
vector_sqr = vector ** 2
print("Вектор vector після піднесення елементів до квадрату:")
print(vector_sqr)

Вектор vector після піднесення елементів до квадрату:
[[0.35123411]
 [0.22934062]
 [0.4417035 ]
 [0.2223134 ]
 [0.68251285]
 [0.09484295]
 [0.86262192]
 [0.08341492]
 [0.91430372]
 [0.37858493]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
# 1. Множення матриць А і В
result_matrix = np.dot(B, A)
print("Результат множення матриць А і В:")
print(result_matrix)

Результат множення матриць А і В:
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [9]:
# 2. Множення матриці result_matrix на вектор С
result_matrix_C = np.dot(result_matrix, C)
print("Результат множення матриць result_matrix і C:")
print(result_matrix_C)

Результат множення матриць result_matrix і C:
[[0.5202]
 [0.2846]]


In [10]:
# 3. Множення матриці result_matrix на матрицю D
result_matrix_D = np.dot(result_matrix, D)
print("Результат множення матриць result_matrix і D:")
print(result_matrix_D)

Результат множення матриць result_matrix і D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [11]:
# 1. Транспонування матриці result_matrix
result_matrix_T = result_matrix.T
print("Матриця result_matrix транспонована:")
print(result_matrix_T)

Матриця result_matrix транспонована:
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [12]:
# 2. Транспонування вектора vector
vector_T = vector.T
print("Вектор vector транспонований:")
print(vector_T)
print(f"\nРозмір вектора vector транспонованого {vector_T.shape}")

Вектор vector транспонований:
[[0.59265007 0.47889521 0.66460778 0.47150122 0.82614336 0.30796583
  0.92877442 0.28881642 0.9561923  0.61529256]]

Розмір вектора vector транспонованого (1, 10)


In [13]:
# 3. Операція numpy.expand_dims над вектором vector
column_vector = np.expand_dims(vector, axis = 1)
column_vector

array([[[0.59265007]],

       [[0.47889521]],

       [[0.66460778]],

       [[0.47150122]],

       [[0.82614336]],

       [[0.30796583]],

       [[0.92877442]],

       [[0.28881642]],

       [[0.9561923 ]],

       [[0.61529256]]])

In [14]:
# 4. Транспонування вектора column_vector
column_vector_T = column_vector.T
print("Вектор column_vector транспонований:")
print(column_vector_T)
print(f"\nРозмір вектора column_vector транспонованого {column_vector_T.shape}")

Вектор column_vector транспонований:
[[[0.59265007 0.47889521 0.66460778 0.47150122 0.82614336 0.30796583
   0.92877442 0.28881642 0.9561923  0.61529256]]]

Розмір вектора column_vector транспонованого (1, 1, 10)
