В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [1]:
import numpy as np

In [2]:
def sigmoid(z):
    y = 1 / (1 + 1 / np.exp(z))
    return y

In [3]:
sigmoid([-2, -1, 0, 1, 2])

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [4]:
def hypothesis(theta, X):
    z = np.dot(X, theta.T)
    y = sigmoid(z)
    return y

In [5]:
theta = np.array([0.5, -0.5])
X = np.array([[1,2], [1,-1], [1, 0], [1, 1]])
hypothesis(theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [6]:
def compute_gradient(theta, X, y):
    m = X.shape[0]
    h = hypothesis(theta, X)
    g = np.dot(h - y, X) / m
    return g

In [7]:
theta = np.array([0.5, -0.5])
X = np.array([[1,2], [1,-1], [1, 0], [1, 1]])
y = np.array([1, 0, 1, 0])

In [8]:
compute_gradient(theta, X, y)

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [9]:
def full_batch_gradient_descent(X, y, lr = 0.1, epochs = 100):
    X = np.array([[1,2], [1,-1], [1, 0], [1, 1]])
    y = np.array([1, 0, 1, 0])
    theta = np.array([0.0, 0.0]) # початкові значення
    for _ in range(epochs):
        gradient = compute_gradient(theta, X, y)
        theta[0] = theta[0] - lr * gradient[0]
        theta[1] = theta[1] - lr * gradient[1]
    return theta

In [10]:
predict_theta = full_batch_gradient_descent(X, y)
predict_theta

array([-0.2893693 ,  0.77655125])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [11]:
# Функція для обчислення ймовірностей належності кожного з екземплярів в матриці Х до класу 1 при знайдених параметрах theta

def predict_proba(theta, X):
    h = hypothesis(theta, X)
    return h

In [12]:
# Функція для визначення класу кожного екземпляра з матриці Х з передбаченої ймовірності належності екземпляра до класу 1

def predict(theta, X, threshold = 0.5):
    predict_class = []
    predicts = predict_proba(predict_theta, X)
    for predict in predicts:
        if predict < threshold:
            predict_class.append(0)
        else:
            predict_class.append(1)
    return predict_class

In [13]:
# Функція для обчислення точності моделі як частки правильно передбачених класів 

def accuracy(y_true, y_pred):
    indicator = []
    m = len(y) # величина набору
    for i in range(0, m):
        if y_pred[i] == y[i]:
            indicator.append(1)
        else:
            indicator.append(0)
    a = sum(indicator) / m
    return a

In [14]:
# Обчислення ймовірностей належності кожного з екземплярів в матриці Х до класу 1 при знайдених параметрах theta
predict_proba(predict_theta, X)

array([0.77966809, 0.25617965, 0.42815828, 0.61944235])

In [15]:
# Визначення класу кожного екземпляра з матриці Х з передбаченої ймовірності належності екземпляра до класу 1
y_pred = predict(predict_theta, X, threshold = 0.5)
y_pred

[1, 0, 0, 1]

In [16]:
# Обчислення точності моделі як частки правильно передбачених класів
accuracy(y, y_pred)

0.5